version: "3.8"

services:
  keycloak:
    build: .
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_PORT: "8080"
      KC_PROXY: edge
      KC_HTTP_ENABLED: "true"
      DEBUG_PORT: "*:8787"
    command:
      - "start-dev"
      - "--debug"
    volumes:
      - ./keycloak/conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties:ro
    depends_on:
      - userli

  userli:
    image: mariadb:10.3
    environment:
      MYSQL_USER: mail
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mail
      MARIADB_RANDOM_ROOT_PASSWORD: true
    volumes:
      - ./mariadb/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - userli:/var/lib/mysql

networks:
  default:
    name: keycloak

volumes:
  userli:
