name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Test
        run: mvn -B test

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Build
        run: mvn -B package -DskipTests
