name: Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Test
        run: mvn -B test

  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Build
        run: mvn -B package -DskipTests

  automerge:
    name: Merge Automatically
    needs: [test, build]
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Obtain Access Token
        id: acces_token
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.SYSTEMLI_APP_CREDENTIALS_TOKEN }})"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Merge
        uses: fastify/github-action-merge-dependabot@73ec4cbb5e56df5591eae286972d5b2201ffe90f # v3.15.0
        with:
          github-token: ${{ steps.acces_token.outputs.token }}
