name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}

      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Build
        run: mvn -B package -DskipTests

      - name: Upload artifact to release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          append_body: true
          files: |
            target/userli-storage-provider-1.0.0.jar
          tag_name: ${{ github.ref_name }}
          token: ${{ github.token }}
