name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 17
          cache: "maven"

      - name: Download dependencies
        run: mvn -B dependency:go-offline

      - name: Build
        run: mvn -B package -DskipTests

      - name: Zip artifacts
        working-directory: target
        run: zip -r userli-storage-provider.zip *.jar

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          files: |
            target/userli-storage-provider.zip
          tag_name: ${{ github.ref_name }}
          token: ${{ github.token }}
